name: Deploy Cloud Function

on:
  push:
    branches:
      - 'main'

jobs:
  all:
    name: CI/CD workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via Pterodactyl actions
        uses: JustArtiom/ptero-deploy@v1
        with:
          url: ${{ secrets.PTERO_URL }}
          api_key: ${{ secrets.PTERO_API_KEY }}
          server_id: ${{ secrets.PTERO_SERVER }}
          base_path: ./dist
          clean: true
          run: |
            npm install
            node index.js